name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r todo-backend/requirements.txt

      # - name: Run backend tests
      #   run: |
      #     cd todo-backend
      #     pytest

      - name: Build Docker image for backend
        run: |
          cd todo-backend
          docker build -t todo-backend .

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd todo-frontend
          npm install

      # - name: Run frontend tests
      #   run: |
      #     cd todo-frontend
      #     npm run test:unit

      - name: Build Docker image for frontend
        run: |
          cd todo-frontend
          docker build -t todo-frontend .
